on: push
name: Publish Website
jobs:
  FTP-Deploy-Action:
    name: FTP-Deploy-Action
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.1.0
      with:
        fetch-depth: 2
    - name: FTP-Deploy-Action
      uses: SamKirkland/FTP-Deploy-Action@3.1.1
      with:
        ftp-server: ftp://54.39.68.61:21/degraded_minigame/datapacks
        ftp-username: redstonecharger@gmail.com.46593
        ftp-password: ${{ secrets.FTP_PASSWORD }}
        local-dir: ./
        
